###
POST https://adminstlv2.up.railway.app/api/login
Content-Type: application/json

{
  "username": "john",
  "password": "john"
}

###
DELETE https://adminstlv2.up.railway.app/api/logout
Content-Type: application/json
Authorization: Bearer 68|jjIFq2kjnRgmsxJHPL89qylFf4BMkplVK6DDWDmC

###
POST https://adminstlv2.up.railway.app/api/Agent/Results
Authorization: Bearer 68|jjIFq2kjnRgmsxJHPL89qylFf4BMkplVK6DDWDmC
Content-Type: application/json

###
POST https://adminstlv2.up.railway.app/api/Agent/Reports
Authorization: Bearer 68|jjIFq2kjnRgmsxJHPL89qylFf4BMkplVK6DDWDmC
Content-Type: application/json

###
POST https://adminstlv2.up.railway.app/api/Agent/Transactions
Authorization: Bearer 68|jjIFq2kjnRgmsxJHPL89qylFf4BMkplVK6DDWDmC
Content-Type: application/json

###
POST https://adminstlv2.up.railway.app/api/Agent/Transactions/d5daa-99117010
Authorization: Bearer 68|jjIFq2kjnRgmsxJHPL89qylFf4BMkplVK6DDWDmC
Content-Type: application/json


###
POST https://adminstlv2.up.railway.app/api/Agent/Bets/v2
Authorization: Bearer 68|jjIFq2kjnRgmsxJHPL89qylFf4BMkplVK6DDWDmC
Content-Type: application/json

{
  "game_type": "S3",
  "draw_time": "2pm",
  "combinations": [{"number": "899", "bet": "2"}],
  "phone_number": "09545675865"
}
