POST http://localhost:3000/signup
Content-Type: application/json

{
  "username": "luffy",
  "first_name": "sanji",
  "last_name": "sanji",
  "address": "sanji",
  "password": "sanji"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "zoro",
  "password": "zoro"
}


###

GET http://localhost:3000/me


###

POST http://localhost:3000/contact
Content-Type: application/json

{
  "first_name": "ussop",
  "last_name": "ussoplast",
  "email": "ussop@gmail.com",
  "phone": "09501296660",
  "address": "butuan"
}

###
GET http://localhost:3000/contact
Content-Type: application/json

###
DELETE http://localhost:3000/contact
Content-Type: application/json

{
  "id": 25
}

###
PUT  http://localhost:3000/contact/88
Content-Type: application/json

{
  "first_name": "zzzz",
 "last_name": "ussoplast",
  "email": "ussop@gmail.com",
   "phone": "234",
    "address": "aclan"
}

###
PUT http://localhost:3000/user
Content-Type: application/json

{
  "username": "madara",
  "first_name": "wdwdw",
  "last_name": "Soroysoroy",
  "address": "Maon, Villa Kananga Butuan City"
}



###
GET http://localhost:3000/search/o
