###
POST https://adminstlv2.up.railway.app/api/login
Content-Type: application/json

{
  "username": "john",
  "password": "john"
}

###
DELETE https://adminstlv2.up.railway.app/api/logout
Content-Type: application/json
Authorization: 40|gJEt1v6TboPJoiAGWvMHhflJpsKc8UUEgrsgNXOi

###
POST https://adminstlv2.up.railway.app/api/Agent/Results
Authorization: 40|gJEt1v6TboPJoiAGWvMHhflJpsKc8UUEgrsgNXOi
Content-Type: application/json

###
POST https://adminstlv2.up.railway.app/api/Agent/Transactions
Authorization: 40|gJEt1v6TboPJoiAGWvMHhflJpsKc8UUEgrsgNXOi
Content-Type: application/json


###
POST https://adminstlv2.up.railway.app/api/Agent/Bets/v2
Authorization: 32|BXaO0ynDbuzzlhFEWXJCVoEKkfn9Q1IPOXJS9iTP
Content-Type: application/json

{
  "game_type": "S3",
  "draw_time": "5pm",
  "combinations": [{"number": "899", "bet": "2"}],
  "phone_number": "+639545675865",
}

###
POST https://adminstl.up.railway.app/api/login
Content-Type: application/json

{
  "username": "luffy",
  "password": "luffy"
}

###
POST https://adminstl.up.railway.app/api/Agent/Results
Authorization: Bearer 493|88FB35myWef9ODH1zYL8gY0XtXaaVE84tV8cxq8a
Content-Type: application/json

###
POST https://adminstl.up.railway.app/api/Agent/Transactions
Authorization: Bearer 493|88FB35myWef9ODH1zYL8gY0XtXaaVE84tV8cxq8a
Content-Type: application/json

###
POST https://adminstl.up.railway.app/api/Agent/Bets/v2
Authorization: Bearer 493|88FB35myWef9ODH1zYL8gY0XtXaaVE84tV8cxq8a
Content-Type: application/json

{
  "game_type": "S3",
  "draw_time": "5PM",
  "combinations": [
    {
    "number": "543",
    "bet": "2"
  }
  ],
}